### ISSUE TITLE
Failed to convert docx to pdf

### ISSUE THREAD

**Issue by SunjfGitHub** [ONLYOFFICE/DocumentBuilder#117]
my code:  
```js
builder.OpenFile("12.docx");
var oDocumenta = Api.GetDocument();
// GlobalVariable["aaa"] = oDocumenta.ToJSON(true, true, true, true, true, true);

var ca = oDocumenta.GetContent();
builder.SaveFile("pdf", "out.pdf")
builder.CloseFile();
```

but, exec script dir not exist out.pdf ? 
This is what the official website demo says:
![2023-11-17_13-26](https://github.com/ONLYOFFICE/DocumentBuilder/assets/16753668/490319b6-823f-407c-80d6-d1113f05c744)

only office version : 
```bash
documentbuilder -v

v7.5.0.128
sdk version:  7.5.0 (build:128)
```

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
