### ISSUE TITLE
poor performance when converting doc to pdf

### ISSUE THREAD

**Issue by lqzerogg** [ONLYOFFICE/DocumentBuilder#133]
**Describe your problem**:
I am keen on harnessing the capabilities of OnlyOffice to produce PDF documents for my clients. Despite an overwhelmingly positive overall experience, I've stumbled upon a performance hurdle when converting .docx files to .pdf on my server, which is noticeably sluggish.
From builder.sever part, I see the example code of using document builder. Like below:

`
// from document builder server
var BuildFile = function (inputFilePath, outputFilePath) {

child_process.execFileSync(builderPath, [inputFilePath], { cwd: path.dirname(builderPath) });

try {
fileSystem.accessSync(outputFilePath, fileSystem.F_OK);
} catch (e) {
throw "An error has occurred. Result File not found";
}
};`

It appears I'd have to initiate a separate process for each document conversion. Is it possible to launch a single child process and instruct it to carry out document conversions through Inter-Process Communication (IPC)? I'm dealing with hundreds of requests instantaneously and need to convert several hundred documents each second. Enhancing performance to reduce server resource consumption is crucial for me.

*Be clear in your description of the problem.*
It appears I'd have to initiate a separate process for each document conversion.

**DocumentBuilder version**:
newest

**Installation method**:
apt get install

**Operating system**:
linux

**Comment by askonev** [comment]
@lqzerogg at the moment, the InterProcess Communication (IPC) interface is not implemented for documentbuilder

Also, conversion to pdf is one of the most loaded due to the use of the js engine for document recalculation

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.

**Comment by lqzerogg** [comment]
so sad

> @lqzerogg at the moment, the InterProcess Communication (IPC) interface is not implemented for documentbuilder
> 
> Also, conversion to pdf is one of the most loaded due to the use of the js engine for document recalculation

sad
