### ISSUE TITLE
Windows document builder cause MSVCR100.dll error

### ISSUE THREAD

**Issue by ShockwaveNN** [ONLYOFFICE/DocumentBuilder#2]
1. Install current dev doc builder http://repo-doc-onlyoffice-com.s3.amazonaws.com/windows/onlyoffice-documentbuilder/origin/develop/latest/x86/onlyoffice-documentbuilder-4.4.1.35-x86.exe
2. Run `C:\ONLYOFFICE\DocumentBuilder\samples.bat`

Result:
```
---------------------------
x2t.exe - System Error
---------------------------
The code execution cannot proceed because MSVCR100.dll was not found. Reinstalling the program may fix this problem. 
---------------------------
OK   
---------------------------
```

Tested on:
Win 10 x64

**Comment by ShockwaveNN** [comment]
Same error on Win 10 x64 with x64 builder 
http://repo-doc-onlyoffice-com.s3.amazonaws.com/windows/onlyoffice-documentbuilder/origin/develop/latest/x64/onlyoffice-documentbuilder-4.4.1.35-x64.exe

**Comment by ShockwaveNN** [comment]
`icu` dll require old version of msvcr
icu was downloaded precomplied according to https://github.com/ONLYOFFICE/core/blob/master/Common/3dParty/icu/fetch.bat#L21
Need to use newer version, that stored in svn or compile it by ourselfs

**Comment by ShockwaveNN** [comment]
Fixed in https://github.com/ONLYOFFICE/document-builder-package/commit/79504973870d0622f4d83a1561554540896b0c20

**Comment by ShockwaveNN** [comment]
Proplem not reproduced on:
http://repo-doc-onlyoffice-com.s3.amazonaws.com/windows/onlyoffice-documentbuilder/origin/develop/latest/x86/onlyoffice-documentbuilder-4.4.1.36-x86.exe

**Comment by agolybev** [comment]
It isn't reproduced, it's fixed.

**Comment by ShockwaveNN** [comment]
@agolybev need to check x64 version. Working on it now

**Comment by ShockwaveNN** [comment]
http://repo-doc-onlyoffice-com.s3.amazonaws.com/windows/onlyoffice-documentbuilder/origin/develop/latest/x64/onlyoffice-documentbuilder-4.4.1.36-x64.exe
Works fine too.
Closing issue
