### ISSUE TITLE
Call `Api.CreateImage` with url result broken file on Windows

### ISSUE THREAD

**Issue by ShockwaveNN** [ONLYOFFICE/DocumentBuilder#26]
1. Run this script on Windows

```
builder.CreateFile("docx");
var oDocument = Api.GetDocument();
var oParagraph, oDrawing;
oParagraph = oDocument.GetElement(0);
oDrawing = Api.CreateImage("https://api.onlyoffice.com/content/img/docbuilder/examples/coordinate_aspects.png", 60 * 36000, 35 * 36000);
oParagraph.AddDrawing(oDrawing);
builder.SaveFile("docx", "CreateImage.docx");
builder.CloseFile();
```

In result will be created broken file of 1KB size.

This issue only actual on Windows, on centos and ubuntu everything is fine.
Also `Api.CreateImage` will not result broken file if use base64 inside

Tested on:
```
Windows 10
v5.3.3.30
sdk version:  5.3.3 (build:61)
```

**Comment by TangF** [comment]
Has this bug been solved, please?

**Comment by ShockwaveNN** [comment]
Sorry, this issue is still actual in v6.0.0 of DocumentBuilder (will be released very soon)
This issue require some addition functions to be implemented on Windows

If this is critical for you - you can use base64 encoding to create image, or use Linux version for thich this bug is not actual

**Comment by TangF** [comment]
> 抱歉，此问题在DocumentBuilder v6.0.0中仍然存在（将很快发布）。
> 此问题需要在Windows上实现一些附加功能
> 
> 如果这对您很重要-您可以使用base64编码来创建映像，或者使用Linux版本来解决此错误，

ok, thanks

**Comment by TangF** [comment]
> Sorry, this issue is still actual in v6.0.0 of DocumentBuilder (will be released very soon)
> This issue require some addition functions to be implemented on Windows
> 
> If this is critical for you - you can use base64 encoding to create image, or use Linux version for thich this bug is not actual

ok, thanks.

**Comment by ShockwaveNN** [comment]
I've created issue 54528 in our private issue tracker

Nothing changed for issue by itself, but we change our bug tracking guidelines since original issue was filed in 2019
Problem actual in current stable version of DocumentBuilder on windows

**Comment by askonev** [comment]
bug is not repeated on the version:

```shell
windows 10
v7.5.0.128
sdk version:  7.5.0 (build:128)
```

**Comment by Rita-Bubnova** [comment]
I close this issue. Feel free to comment or reopen it if you got further questions.
