### ISSUE TITLE
Couldn't create temp folder under non-root user

### ISSUE THREAD

**Issue by szutt** [ONLYOFFICE/DocumentBuilder#28]
Hi.

Thanks for this great product. I was trying the first example here https://api.onlyoffice.com/docbuilder/basic but it failed with a regular user with the following error :
```
Couldn't create temps folder
error: : save file error (1)
```
But, if i ran documentbuilder under the root user it works correctly.

I tested with a fresh installation on debian 9 and debian 10 (64 bit).
Adding `builder.SetTmpFolder("DocBuilderTemp");` does not change nothing.

**Comment by ShockwaveNN** [comment]
@szutt Hi, I was able to reproduce your issue with this Dockerfile, thanks

```
FROM debian:10

RUN apt-get update && apt-get -y -q install gnupg2
RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys CB2DE8E5
RUN echo "deb http://download.onlyoffice.com/repo/debian squeeze main" >> /etc/apt/sources.list.d/onlyoffice.list && \
    apt-get -y update && \
    apt-get -y install onlyoffice-documentbuilder

RUN useradd -ms /bin/bash newuser
USER newuser
ADD script.js script.js

CMD documentbuilder script.js
```

```
Couldn't create temp folder
error: : save file error (1)
```

**Comment by ShockwaveNN** [comment]
@szutt 
https://api.onlyoffice.com/docbuilder/basic
This script call `builder.SaveFile("docx", "SampleText.docx");`
This mean `SampleText.docx` saved to current directory (root)

If change to `builder.SaveFile("docx", "/tmp/SampleText.docx");` everything seems fine

**Comment by szutt** [comment]
Thanks a lot! Really!

**Comment by sduensin** [comment]
I'm having the same issue.  I'm trying to write a PDF into a folder I have access to.  Even using `builder.SetTmpFolder("/tmp");` doesn't help.

**Comment by ShockwaveNN** [comment]
@sduensin could you attach whole script, version of DocumntBuilder and platform you are using?

**Comment by sduensin** [comment]
This works:
```
builder.OpenFile("Manual.docx");
builder.SaveFile("pdf", "/tmp/Manual.pdf");
builder.CloseFile();
```
But this does not:
```
builder.OpenFile("Manual.docx");
builder.SaveFile("pdf", "Manual.pdf");
builder.CloseFile();
```

I'm on Linux Mint 19.3 Cinnamon with DocumentBuilder installed from the deb provided on the OO web site:  5.3.3-43

**Comment by ShockwaveNN** [comment]
@sduensin try to use `sudo`, by default if no full path specified

Also 
```
builder.OpenFile("Manual.docx");
builder.SaveFile("pdf", "./Manual.pdf");
builder.CloseFile();
```
should work without sudo

**Comment by sduensin** [comment]
Specifying the current directory with `./` fixed it.  Thank you!

**Comment by flameleo11p** [comment]
this is a bug:
when builder.SaveFile("pdf", "example.pdf");
means builder.SaveFile("pdf", "/root/example.pdf");
but everyone expect 
builder.SaveFile("pdf", "example.pdf");
builder.SaveFile("pdf", "./example.pdf");
works same way .

**Comment by ShockwaveNN** [comment]
@flameleo11p Hi

First of all - I've already created bug about removing requiring `sudo` for run scripts (bug 54401 in our private issue tracker)

But for your example (ignoring requiring sudo)
If I'm in folder  
```
$ cd ~/sources/doc-builder-testing/asserts/js/other_formats
$ cat addtext_pdf.js 
builder.CreateFile("docx");
var oDocument = Api.GetDocument();
var oParagraph = oDocument.GetElement(0);
oParagraph.AddText("This is just a sample text. Nothing special.");
builder.SaveFile("pdf", "AddText.pdf");
builder.CloseFile();
$ sudo documentbuilder addtext_pdf.js
$ ls -la AddText.pdf 
-rw-r--r-- 1 root root 23688 дек 14 10:50 AddText.pdf
```
This script correctly creates file in current working directory
