### ISSUE TITLE
DocumentBuilder  generate file success but the  content is empty

### ISSUE THREAD

**Issue by lugeluge** [ONLYOFFICE/DocumentBuilder#29]
I successfully compiled the douctment builder and successfully ran the examples in it, but when I used c++ API to generate files, I also successfully compiled the project use vs2017 win10, but the contents of the  files are empty, including docx, rtf, txt and so on.
the cpp example is coppy from https://api.onlyoffice.com/docbuilder/integrationapi/cdocbuilder

![image](https://user-images.githubusercontent.com/16603407/64062162-e7fce180-cc15-11e9-9cd0-518773dc0979.png)
the file can generate but the content is empty.the docbuilder.exe can successfully to gengerate the samples
![image](https://user-images.githubusercontent.com/16603407/64062259-f5669b80-cc16-11e9-8a0d-52301bc24739.png)
i have no idea about how to sove it,Is there anything wrong  in cpp file?

**Comment by lugeluge** [comment]
Still unresolved

**Comment by lugeluge** [comment]
the command is undefined
![image](https://user-images.githubusercontent.com/16603407/64248484-c9fbed80-cf43-11e9-8f5e-4f72b67cf955.png)

**Comment by K0R0L** [comment]
We cannot repeat this. Сan you send your full (portable) program?

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
