### ISSUE TITLE
Cenots 8 fonts requirements not match

### ISSUE THREAD

**Issue by ShockwaveNN** [ONLYOFFICE/DocumentBuilder#31]
1. `sudo dnf -y install epel-release`
2. `sudo dnf -y install https://download.onlyoffice.com/repo/centos/main/noarch/onlyoffice-repo.noarch.rpm`
3. `sudo dnf -y install onlyoffice-documentbuilder`

Result:
```
Error: 
 Problem: conflicting requests
  - nothing provides dejavu-lgc-sans-fonts needed by onlyoffice-documentbuilder-5.3.3-43.x86_64
  - nothing provides dejavu-lgc-sans-mono-fonts needed by onlyoffice-documentbuilder-5.3.3-43.x86_64
  - nothing provides dejavu-lgc-serif-fonts needed by onlyoffice-documentbuilder-5.3.3-43.x86_64
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
[virtualbox@localhost ~]$ sudo dnf -y install onlyoffice-documentbuilder
Failed to set locale, defaulting to C
Last metadata expiration check: 0:00:58 ago on Fri Oct 25 10:54:45 2019.
Error: 
 Problem: conflicting requests
  - nothing provides dejavu-lgc-sans-fonts needed by onlyoffice-documentbuilder-5.3.3-43.x86_64
  - nothing provides dejavu-lgc-sans-mono-fonts needed by onlyoffice-documentbuilder-5.3.3-43.x86_64
  - nothing provides dejavu-lgc-serif-fonts needed by onlyoffice-documentbuilder-5.3.3-43.x86_64
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
```

Seems this error happened after some updates of repos, on 2019.10.16 with `Centos:8` docker image everything was fine (https://github.com/ONLYOFFICE/doc-builder-testing/pull/257)

**Comment by e-alfred** [comment]
The problem still exists with Centos 8.1/RHEL 8.1. It would be good to fix this for both.

**Comment by agolybev** [comment]
It works for me.
I've checked it twice. First on VM with official centos iso. Second on docker image `centos:8`.

**Comment by ShockwaveNN** [comment]
@agolybev can confirm DocumentBuilder installing ok on CentOS 8 VirtualBox, and `centos:8` docker image

@e-alfred please retry your installation by now, also as far as I understand there is no such thing as Centos 8.1. If issue still exist - comment it here and I reopen this issue

**Comment by ShockwaveNN** [comment]
Can confirm again on current centos 8 virtualbox with all updates on 2020.01.19
Same for `centos:8` docker image (id `470671670cac`)
:(

**Comment by ShockwaveNN** [comment]
Seems we need to remove those dependencies @agolybev

**Comment by agolybev** [comment]
Fixed by https://github.com/ONLYOFFICE/document-builder-package/commit/d32ff4b438b14c8da9790685f66969553439687c#diff-ac04c6910d5460a60ded618a70c20adf

**Comment by ShockwaveNN** [comment]
DocumentBuilder v6.0.0 is released

This issue should be fixed
