### ISSUE TITLE
Paste with Ctrl + Shift + V without formatting

### ISSUE THREAD

**Issue by itsyshaus** [ONLYOFFICE/DocumentBuilder#34]
Often i want to copy and paste text without formattig with the shortcut "Ctrl + Shift + V", like in M$ word or google docs, but this does not work with Only Office. Would be nice to get this function here to in near future.

Only workarround i know, is to use notepad to remove the old formatting and paste again from there.

**Comment by KirillovIlya** [comment]
There is such functionality. 

We have the special paste button for this purpose
![image](https://user-images.githubusercontent.com/17902914/78368334-243d5980-75cc-11ea-843d-8f2b3f68db93.png)

Ctrl + Shift + V has a different meaning, it paste text formatting, that was previously copied.

**Comment by sk1806** [comment]
This is incredibly inconvenient though.  Could a keyboard shortcut be introduced?

Actually, Ctrl + Shift + V   seems to do nothing at all, so I assume it is free to be used for 'paste without formatting', making it the same as MS word, google docs and libre office etc.  This would be really handy.

**Comment by mehelme** [comment]
+1 vote  for Ctrl + Shift + V

**Comment by ShockwaveNN** [comment]
I don't know how this issue rleated to DocumentBuilder

Correct place for this issue (and there is already one) - https://github.com/ONLYOFFICE/DocumentServer/issues/1002
