### ISSUE TITLE
AppImage

### ISSUE THREAD

**Issue by mlunax** [ONLYOFFICE/DocumentBuilder#41]
Is possible to make AppImage version?
I would like to see it, I am not using RPM or DEB systems.

**Comment by ShockwaveNN** [comment]
Thank you for your idea, I like it

I created a new issue 47255, in our private issue tracker for discuss of this task.
But I cannot guarantee you any time table for it's implementation

**Comment by ShockwaveNN** [comment]
Implemented [here](https://github.com/ONLYOFFICE/appimage-documentbuilder)

We'll release v7.1.0 soon, but right now v7.0.0 already available
