### ISSUE TITLE
ContentControl delete invalid

### ISSUE THREAD

**Issue by verydemo** [ONLYOFFICE/DocumentBuilder#56]
- builder version
![image](https://user-images.githubusercontent.com/29354679/117534437-0d193880-b024-11eb-9570-f1883b99b794.png)

- my code
![image](https://user-images.githubusercontent.com/29354679/117534538-6bdeb200-b024-11eb-80a5-f9578b280179.png)

```
builder.OpenFile("test1.docx");
oDocument = Api.GetDocument();
oContentControls = oDocument.GetAllContentControls();
for (var i = oContentControls.length-1; i >= 0;i--)
{
    oContentControls[i].Delete(false);
}

oContentControls1 = oDocument.GetAllContentControls();
console.log("oContentControls1[0].GetClassType()");
console.log(oContentControls1[0].GetClassType());
console.log("oContentControls1.length")
console.log(oContentControls1.length)

builder.SaveFile("docx", "test2nocc.docx");
builder.CloseFile();
```

- i want to delete ContentControl. it run no problem, but it is invalid.

- print message

    oContentControls1[0].GetClassType()
    blockLvlSdt
    oContentControls1.length
    249

![image](https://user-images.githubusercontent.com/29354679/117534558-78fba100-b024-11eb-89a8-02d1cc31557f.png)

**Comment by ShockwaveNN** [comment]
Hi, could you attach original  tests1.docx you want to edit?
