### ISSUE TITLE
Unable to control formatting of multi-line text cells

### ISSUE THREAD

**Issue by jbigler** [ONLYOFFICE/DocumentBuilder#58]
When creating a Spreadsheet in OnlyOffice (or Calc, Excel, etc), it is possible to use Alt+Enter to add multiple lines of text to a single cell. When this is done, it is possible to highlight and format the individual lines, even individual characters within the cell.

DocumentBuilder allows me to use "\n" to force new lines in the value of a cell. But it doesn't seem possible to control the formatting beyond the level of the entire cell.

Using DocumentBuilder 6.2.0.123
Using Debian Linux

**Comment by ShockwaveNN** [comment]
@askonev please take a look at this issue, I've searched https://api.onlyoffice.com/docbuilder/spreadsheetapi but seems there is no such ability, could you clarify this and create issue for our dev team to implement one if there is no such thing

**Comment by askonev** [comment]
Hello @jbigler! Thanks for your issue. I created a bug `#51432` in our closed tracker.

**Comment by trofim24** [comment]
Have been [fixed](https://github.com/ONLYOFFICE/sdkjs/commit/a346b37b3074d99a84b52c42595cdc3ca0f97bfc) and released in version 7.0.0
