### ISSUE TITLE
Windows - registration.exe corrupted and unreadable

### ISSUE THREAD

**Issue by ShockwaveNN** [ONLYOFFICE/DocumentBuilder#7]
1. Install current dev doc builder http://repo-doc-onlyoffice-com.s3.amazonaws.com/windows/onlyoffice-documentbuilder/origin/develop/latest/x86/onlyoffice-documentbuilder-4.4.1.38-x86.exe
2. Run C:\ONLYOFFICE\DocumentBuilder\registration.exe

```
[Window Title]
C:\ONLYOFFICE\DocumentBuilder\registration.exe

[Content]
C:\ONLYOFFICE\DocumentBuilder\registration.exe

The file or directory is corrupted and unreadable.


[OK]
```
Tested on:
Win 10 x64

**Comment by agolybev** [comment]
Fixed. Need to rebuild.

**Comment by ShockwaveNN** [comment]
Not reproduced in http://repo-doc-onlyoffice-com.s3.amazonaws.com/windows/onlyoffice-documentbuilder/origin/develop/latest/x86/onlyoffice-documentbuilder-4.4.1.40-x86.exe
