### ISSUE TITLE
How can I batch operate Spreadsheet cells

### ISSUE THREAD

**Issue by p294960570** [ONLYOFFICE/DocumentBuilder#75]
i want to change Multiple cells'value
like 
change
    A       B
1   a       b
2  c       d
to
    A       B
1   e       f
2  g        h

i need use SetValue() four times

is it possible 
oWorksheet.GetRange("A1:B2").SetValue("e","f","g","h");

because i found documentbuilder spend to much time, and more script more time

**Comment by p294960570** [comment]
> > oWorksheet.GetRange("A1:B2").SetValue("e","f","g","h");
> 
> I don't think so, SetValue can get only one argument
> 
> > because i found documentbuilder spend to much time, and more script more time
> 
> I think even if we introduce new method - if sill took same time to replace as calling SetValue 4 times
> 
> > SetValue("e","f","g","h")
> 
> Is there any kind of analog in Microsoft's macroses?

This is a pity. Thank you for your reply

**Comment by ShockwaveNN** [comment]
If you can provide file and script for which replacement took a lot of time - maybe I can ask developers if we can improve speed of this

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
