### ISSUE TITLE
Chart Data in Presentation is not Editable

### ISSUE THREAD

**Issue by CKolkey** [ONLYOFFICE/DocumentBuilder#76]
I'm following the presentation chart api documentation: (https://api.onlyoffice.com/docbuilder/presentationapi/api/createchart)
```
builder.CreateFile("pptx");
oPresentation = Api.GetPresentation();
oSlide = oPresentation.GetSlideByIndex(0);
oSlide.RemoveAllObjects();
oShape = Api.CreateChart("bar3D", [
  [200, 240, 280],
  [250, 260, 280]
], ["Projected Revenue", "Estimated Costs"], [2014, 2015, 2016], 4051300, 2347595, 24);
oShape.SetSize(300 * 36000, 130 * 36000);
oShape.SetPosition(608400, 1267200);
oSlide.AddObject(oShape);
builder.SaveFile("pptx", "CreateChart.pptx");
builder.CloseFile();
```

I've created a presentation without issue and the pptx file is viewable in powerpoint. However, if I right click on the resulting chart and try to edit the data, I'm met with the following error:
<img width="495" alt="Screenshot 2022-02-15 at 17 00 05" src="https://user-images.githubusercontent.com/7228095/154099951-092cdcf9-20eb-4f94-9c45-df615cd8e112.png">

This happens on both windows and macos, on both my local machine and on the onlyoffice api documentation page (link above).

For fun, I opened up the pptx (zip) file to see if there was an embedded xlsx file, and sure enough, it's there. The relation ID's seem to be correct, too. _However_ when I attempt to open the xlsx file on its own in excel, I'm being told that there are issues with the file, and that excel needs to repair it. Here's the repair log:

```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<recoveryLog xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">
	<logFileName>Repair Result to Microsoft_Excel_Worksheet10.xml</logFileName>
	<summary>Errors were detected in file ’/Users/cameron/Downloads/presentation - 2022-02-15T163131.751/ppt/embeddings/Microsoft_Excel_Worksheet1.xlsx’</summary>
	<repairedRecords summary="Following is a list of repairs:">
		<repairedRecord>Repaired Records: Table from /xl/tables/table1.xml part (Table)</repairedRecord>
	</repairedRecords>
</recoveryLog>
```

Now here's the real trick: this occurs when using the API page I linked to above. The chart data is editable in your webapp, but not in powerpoint or excel, so I feel confident that the issue is not in my local setup.

**Steps to reproduce the problem**:
1. Visit: https://api.onlyoffice.com/docbuilder/presentationapi/api/createchart
2. Download file as pptx
3. Attempt to edit chart data in powerpoint (right click chart > edit data)
4. See issue

For posterity, here is the setup I am using locally:

**DocumentBuilder version**: v7.0.0.132 (sdk version:  7.0.0 (build:132))

**Installation method**:  https://www.onlyoffice.com/en/download.aspx#builder (for centos)

**Operating system**: linux/centos

I've also attached an offending pptx file, though it's the exact one downloaded from your api docs.
[Example Title.pptx](https://github.com/ONLYOFFICE/DocumentBuilder/files/8072825/Example.Title.1.pptx)

**Comment by l8556** [comment]
Hi @CKolkey 

Thank you for your issue
I can confirm - this is a bug. Issue 55567 in our private issue tracker.

**Comment by CKolkey** [comment]
Outstanding, thanks for the quick response. Out of curiosity, do you have any kind of rough timeline for a fix?

**Comment by l8556** [comment]
Sorry I'm just a QA guy and cannot provide any time frames to any fix

If you really need this problem fixed - better to contact sales@onlyoffice.com or support@onlyoffice.com if you're already a paying customer.

**Comment by CKolkey** [comment]
Will do, thanks.

**Comment by l8556** [comment]
Hi @CKolkey 

We fixed this issue at[ fix bug #55567 ](https://github.com/ONLYOFFICE/core/commit/b22eeeab9db66ae8352fe60a642fcd4d4c1db3ff)
This will be released as 7.1.0, but I cannot give ETA for this release.

**Comment by CKolkey** [comment]
I really appreciate the fast turnaround - thanks!

**Comment by ShockwaveNN** [comment]
I'll leave this issue opened until we'll release this fix

**Comment by ShockwaveNN** [comment]
DocumentBuilder v7.1 is released and this issue should be fixed. I'm closing it, feel free to comment or create new if got any troubles
