### ISSUE TITLE
Feature Request: Support for Forms

### ISSUE THREAD

**Issue by jasle** [ONLYOFFICE/DocumentBuilder#81]
ONLYOFFICE Docs v7.0 comes support for creating fillable forms. 

It would be great if the Document Builder would also support generating forms.

**Comment by ShockwaveNN** [comment]
Hi, to be clear - are you want a ability to create docxf files using WebBuilder

If so - I'll agree, seems there is no API right now to do that

**Comment by jasle** [comment]
Hi, thanks for your reply @ShockwaveNN !

You are right - I want the ability to create docxf files and export them to an oform or pdf file using the DocumentBuilder API.

**Comment by ShockwaveNN** [comment]
Thanks for you idea, I've created issue 56479 in our private issue tracker to discuss it with our team

**Comment by ShockwaveNN** [comment]
Methods for generating forms will be added in v7.1
It will be first version with those methods so they be little bit raw, but we'll continue to improve them

I really hope we released v7.1 in a week or two

**Comment by ShockwaveNN** [comment]
DocumentBuilder v7.1 is released and methods [are added](https://api.onlyoffice.com/docbuilder/formapi)

I'll close this issue, I think if some troubles arise - better to create a new issue with specific scnearios
